spring:

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
            clientId: 141656860370-gtcshv7ugcrvu8eii2vt2l6tqqg5uv3d.apps.googleusercontent.com
            clientSecret: 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
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true